name: Publish to VSCode Store
on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  package-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g @vscode/vsce pnpm
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile --ignore-scripts
      - run: vsce package --no-dependencies
      - uses: actions/upload-artifact@v4.0.0
        with:
          path: '*.vsix'
      - run: vsce publish --no-dependencies -p $TOKEN
        env:
          TOKEN: ${{ secrets.VSCODE_PUBLISH_TOKEN }}
